### ISSUE TITLE
Documentation, API

### ISSUE THREAD

**Issue by edencakir** [ronak301/react-native-submit-button#1]
Although it's a great component, I think you better write a public API including color modifications, animation durations etc.

**Comment by ronak301** [comment]
Sure. Will Update soon.

**Comment by ronak301** [comment]
I have updated some docs and some API. So it is in usable state now. Props need to be documented. More API's will be added soon.

**Comment by edencakir** [comment]
Perfect, appreciate it.

**Comment by ronak301** [comment]
Thanks.
