### ISSUE TITLE
Wrong display

### ISSUE THREAD

**Issue by quangtruong16994** [ronak301/react-native-submit-button#2]
How can i fix this?
![capture](https://cloud.githubusercontent.com/assets/16751293/21958697/cd559b88-dae6-11e6-8276-9aad7c783687.PNG)

**Comment by ronak301** [comment]
can u please tell the steps to reproduce this.

**Comment by quangtruong16994** [comment]
@ronak301 I just `import SubmitButton from 'react-native-submit-button';` and call `<View style={{flex:1}}>
        <SubmitButton />
      </View>`

**Comment by ronak301** [comment]
Can u please try now. I have updated.

**Comment by quangtruong16994** [comment]
The same, I'm using android simulator 4.2.2

**Comment by ronak301** [comment]
Please follow below steps : 
1 ) remove react-native-submit-button from node modules.
2 ) remove entry from package.json
3 ) run npm install --save react-native-submit-button
4 ) rnpm link
