### ISSUE TITLE
Failed prop type: checker is not a function + 2 other warnings

### ISSUE THREAD

**Issue by ixje** [ronak301/react-native-submit-button#3]
3 warnings are thrown using version 1.0.5

**Warning 1**
Console shows the warning: 
> Failed prop type: checker is not a function

caused by
`buttonState: PropTypes.oneOfType( [ 'normal', 'success', 'error' ] ),` ([source](https://github.com/ronak301/react-native-submit-button/blob/4e398099f989ff606f3cf113514ad3e786ef8ad9/main.js#L167))

change `oneOfType` to `oneOf` to solve.

**Warning 2**
> Warning: Failed prop type: SubmitButton: prop type `errorColor` is invalid; it must be a function, usually from React.PropTypes.

by `errorColor         : PropTypes.color,` ([source](https://github.com/ronak301/react-native-submit-button/blob/4e398099f989ff606f3cf113514ad3e786ef8ad9/main.js#L177))
apparently .color isn't valid (anymore?)
For now I commented it out, but could be checked using e.g. https://github.com/benwiley4000/react-extra-prop-types/blob/master/lib/validators/isColor.js

**Warning 3**
> Warning: Failed prop type: Invalid prop `opacity` of type `object` supplied to `AnimatedCircularProgress`, expected `number`.
Bad object: {
  "backgroundColor": "transparent",
  "position": "absolute",
  "top": 0,
  "left": 0,
  "opacity": 0
}

Triggered by: https://github.com/ronak301/react-native-submit-button/blob/4e398099f989ff606f3cf113514ad3e786ef8ad9/main.js#L112-L128

by caused by: https://github.com/bgryszko/react-native-circular-progress/blob/3704067904844053a2a955348f884cdef1f64cbb/src/AnimatedCircularProgress.js#L58

**Comment by ronak301** [comment]
All warnings are fixed in latest Version. (1.1.0)
