### ISSUE TITLE
getting errors on console for the package 

### ISSUE THREAD

**Issue by PManager1** [ronak301/react-native-submit-button#5]
![image](https://user-images.githubusercontent.com/1026325/30501667-63964ef8-9a31-11e7-8641-3fd35d8ef1c5.png)

import React from 'react';
import { StyleSheet, Text, View,   TouchableOpacity,
  Animated,
  Dimensions,
  Easing } from 'react-native';

import SubmitButton from 'react-native-submit-button';

import LinearGradient from 'react-native-linear-gradient';
// import { AnimatedCircularProgress } from 'react-native-circular-progress';
import Icon from 'react-native-vector-icons/FontAwesome';

const { width, height } = Dimensions.get('window');
console.disableYellowBox = true;

export default class App extends React.Component {

  constructor() {
    super();
    this.state = {
     buttonState1: 'normal',
      buttonState2: 'normal'
    }
  }

  onSubmit1 = () => {
    // api call
    setTimeout( () => {this.setState({ buttonState1: 'success' })}, 2000); // if success, else this.setState({ buttonState: 'error' })
  }

  onSubmit2 = () => {
    // api call
    setTimeout( () => {this.setState({ buttonState2: 'error' })}, 2000); // if success, else this.setState({ buttonState: 'error' })
  };

  onSuccess = () => {
    // route to next page - may be
    console.log('43-  on success triggered');
  }

  render() {
    return (
      <View style={styles.container}>
        <LinearGradient colors={['#F0C27B', '#4B1248']} style={styles.linearGradient}>
          <View style={styles.seperator}><SubmitButton onSubmit={this.onSubmit1} buttonState={this.state.buttonState1} onSuccess={this.onSuccess} buttonText="Login"/></View>
          <View style={styles.seperator}><SubmitButton onSubmit={this.onSubmit2} buttonState={this.state.buttonState2} onSuccess={this.onSuccess} /></View>
        </LinearGradient>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },

  linearGradient : {
    flex           : 1,
    alignItems : 'center',
    justifyContent: 'center',
    paddingTop: 30,
    backgroundColor: '#F5FCFF',
  },
  buttonContainer: {
    justifyContent: 'center'
  },
  seperator: {
    marginBottom: 30
  },
  button         : {
    height         : 54,
    borderRadius   : 35,
    alignItems     : 'center',
    justifyContent : 'center',
    backgroundColor: 'white'
  },
  text           : {
    fontSize       : 22,
    fontFamily     : 'proximanova-regular',
    color          : 'rgb(30, 205, 151)',
    fontWeight     : 'bold',
    backgroundColor: 'transparent'
  }

});

**Comment by ronak301** [comment]
Fixed in latest version.
