### ISSUE TITLE
Console Errors, isn't refreshing to the checkmark button after completed

### ISSUE THREAD

**Issue by vincentvella** [ronak301/react-native-submit-button#6]
[REDACTED]

**Comment by ronak301** [comment]
i have published new version (1.1.0). Can u check now

**Comment by ronak301** [comment]
I think there might be issue in updating your state of button. Can u please double check.

**Comment by ronak301** [comment]
Closing for now.

**Comment by vincentvella** [comment]
You can delete this issue, I was new to RN and didn't understand what I was doing

**Comment by vincentvella** [comment]
In fact - please delete this issue as it was fixed in the recent update.
